name: Upsert Security Hub suppression entries in DynamoDB table
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - sechub-suppressor/**

env:
  AWS_IAM_ROLE: "arn:aws:iam::xxxxxxxxx:role/GithubActionsSecurityHubSuppressorRole"
  AWS_REGION: "xxxxxx"
  ROLE_SESSION_NAME: github-action-securityhub-suppressor
  SCRIPT_DIR: sechub-suppressor

permissions:
  id-token: write
  contents: read
jobs:
  UpsertDynamoDBTable:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2

      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install required packages
        run: cd $SCRIPT_DIR && pip install -r requirements.txt

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          role-to-assume: ${{ env.AWS_IAM_ROLE }}

      - name: Upsert entries in DynamoDB table
        run: cd $SCRIPT_DIR && python put_suppressions.py
