name: Build and Package Lambdas

on:
  push:
    # branches: Maybe only limit to main instead of all pushes?
    # - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        lambda-name: ["findings-manager-jira", "securityhub-findings-manager"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          cd files/lambda-artifacts/${{ matrix.lambda-name }}
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Lambda deployment package
        run: |
          cd files/lambda-artifacts/${{ matrix.lambda-name }}
          mkdir -p ../../build/${{ matrix.lambda-name }}
          cd venv/lib/python${{ matrix.python-version }}/site-packages
          zip -r ../../../../../../build/${{ matrix.lambda-name }}/lambda_function_${{ matrix.python-version }}.zip .
          cd ../../../../
          zip -g ../../build/${{ matrix.lambda-name }}/lambda_function_${{ matrix.python-version }}.zip -r  * --exclude venv/\*

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.lambda-name }}-${{ matrix.python-version }}
          path: files/build/${{ matrix.lambda-name }}/lambda_function_${{ matrix.python-version }}.zip

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove old build artifacts
        run: |
          rm -rf files/build/

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: files/build/

      - name: Move and rename artifacts
        run: |
          for dir in files/build/*; do
            if [ -d "$dir" ]; then
              lambda_name=$(basename $dir | sed 's/-[0-9]\.[0-9]\+$//')
              mkdir -p files/build/$lambda_name
              for file in $dir/*.zip; do
                mv "$file" "files/build/$lambda_name/"
              done
              rm -r "$dir"
            fi
          done

      - name: Commit deployment packages
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add files/build/**/*.zip
          git commit -m "Add all Lambda deployment packages from previous builds"

      - name: Push deployment packages
        run: |
          git push
